### PR TITLE
Add native lazy loading for thumbnail images

### PR DESCRIPTION
**Pull request by scottmallinson**

### CODE REVIEW

**Comment by georgeolaru** [comment]
@razwan can you please have a look and see if the implementation is ready for merging?

**Comment by razwan** [comment]
@georgeolaru there is nothing inherently wrong with this pull request. But I would like one more think to be added before merging.

@scottmallinson thank you for the initiative! Do you mind adding the loading attribute to the slider widget images also, or did you find any issues with that?

**Comment by scottmallinson** [comment]
@georgeolaru @razwan Thanks for taking a look. Give me the weekend to see how feasible it is to add the loading attribute to the slider widget images.

**Comment by scottmallinson** [comment]
@georgeolaru @razwan To add lazy loading to slider widget images I think it should be a simple case of adding something like `$image.attr('loading', 'lazy');` or `$cardImage.attr('loading', 'lazy');` after either `var $image = $slide.find('.c-hero__image').first();` or `var $cardImage = $image.clone().removeClass('c-hero__image');` in [scripts.js](https://github.com/pixelgrade/felt-free/blob/dev/assets/js/scripts.js).

**Comment by razwan** [comment]
@scottmallinson adding the loading attribute in the hero component does the trick.
https://github.com/scottmallinson/felt-free/blob/lazy-loading-images/components/hero/inc/template-tags.php#L876

**Pull request merged**
